### ISSUE TITLE
Customize the index.html page

### ISSUE THREAD

**Issue by rahogan** [unosquare/passcore#201]
Hello all,

I have the passcore app working perfect. I would like to alter the index.html page and customize it with say our school logo, but I am not able to add the background-image. No matter where I add the bg image code, it does not reflect on the page. I can change the color of the page fine, but does not allow me to add an image. Am I doing something wrong on the HTML side, or will the app simply not let me change or add a background-image? I have the image that I want to use in the assets\images folder and I also have it just in the passcore folder. Neither path i use will reflect the image on the index page. I have to admit, it has been some time since I worked with HTML and I am not very familiar with html5. Any help would be greatly appreciated.

RH

**Comment by geoperez** [comment]
You need to modify the Angular webapp. The index.html is just a placeholder to load the webapp. You need to start checking at: https://github.com/unosquare/passcore/tree/master/src/Unosquare.PassCore.Web/ClientApp/app

**Comment by rahogan** [comment]
Thank you. I was not sure where to look on the site, as I am new to it.

**Comment by diogenes25** [comment]
You could modify the css-body in yout index.html here:
https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/ClientApp/index.html

```css
 body {
            font-family: 'Roboto', sans-serif;
            background-color: #fafafa;
            /* ------ Insert this Line -----*/ 
	    background-image: url('/assets/images/background.jpg');
            margin: 0;
            padding: 0;
        }
```
And copy your image here: https://github.com/unosquare/passcore/tree/master/src/Unosquare.PassCore.Web/ClientApp/assets/images
