### ISSUE TITLE
Docker installation problem

### ISSUE THREAD

**Issue by DSantonastaso** [unosquare/passcore#592]
PassCore Server

OS: Linux UBUNTU 18.04LTS
Provider: Active Directory
Settings file (without sensitive information): n/a
Log file (without sensitive information): n/a
Describe the bug
When running:
docker build --rm -t passcore .

Error:
Sending build context to Docker daemon  787.5kB
Step 1/12 : ARG DOTNET_VERSION=3.1
Step 2/12 : FROM mcr.microsoft.com/dotnet/core/sdk:$DOTNET_VERSION-alpine3.9 AS build
manifest for mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.9 not found: manifest unknown: manifest tagged by "3.1-alpine3.9" is not found

**Comment by seancallaway** [comment]
Can confirm same issue.

**Comment by voducthoitc888** [comment]
Same me problem, hope have step on this. thanks !

**Comment by vintury** [comment]
Hello.
Today available `-alpine3.10` you can use this image for build Docker image.

**Comment by mcowart123** [comment]
Trying this again today, and am having this issue (on MacOS 10.15.7):

docker build --rm -t passcore .

Sending build context to Docker daemon  6.291MB
Step 1/12 : ARG DOTNET_VERSION=3.1
Step 2/12 : FROM mcr.microsoft.com/dotnet/core/sdk:$DOTNET_VERSION-alpine AS build
 ---> b003ab77b035
Step 3/12 : RUN apk add --no-cache     icu-libs     nodejs=10.19.0-r0     nodejs-npm
 ---> Running in e6f8595bf961
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  nodejs-12.18.4-r0:
    breaks: world[nodejs=10.19.0-r0]
    satisfies: npm-12.18.4-r0[nodejs]
The command '/bin/sh -c apk add --no-cache     icu-libs     nodejs=10.19.0-r0     nodejs-npm' returned a non-zero code: 2

**Comment by vintury** [comment]
@mcowart123 your ci don't use variable $DOTNET_VERSION, you can see it in your log:

`Step 2/12 : FROM mcr.microsoft.com/dotnet/core/sdk:$DOTNET_VERSION-alpine AS build`

I build image with this docker file:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.10 AS build
RUN apk add --no-cache \
    icu-libs \
    nodejs=10.19.0-r0 \
    nodejs-npm
WORKDIR /build
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /publish /p:PASSCORE_PROVIDER=LDAP

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.10 AS release
WORKDIR /app
COPY --from=build /publish .
EXPOSE 80
CMD ["dotnet", "/app/Unosquare.PassCore.Web.dll"]
```

For run passcore you can use this docker-compose.yaml:
```
version: '2.0'
services:
  passcore:
    container_name: passcore
    image: $your_repo/passcore:latest
    environment:
      - AppSettings__LdapHostnames__0=ad-dc01.example.com
      - AppSettings__LdapPort=389
      - AppSettings__LdapUsername='CN=adm,OU=TechUsers,OU=Users,DC=example,DC=com'
      - AppSettings__LdapPassword='adm_pass'
      - AppSettings__DefaultDomain='example.com'
      - ClientSettings__UseEmail=false
    ports:
      - 80:80
```

But docker file can't work in my infrastructure. I have error: 
`warn: PassCoreLDAPProvider[0]
      Unexpected Win32 API error; error code: 80090308`

Maybe you can get it to work from the container. I could not get.
