### ISSUE TITLE
Docker: Zyborg.PassCore.PasswordProvider.LDAP not found

### ISSUE THREAD

**Issue by hesmar** [unosquare/passcore#614]
**PassCore Server**
- OS: Linux
- Provider: LDAP
- docker-compose.yml: 
```
version: "3.1"

services: 
  passcore:
    image: passcore:latest
    build: ./src 
    restart: always
    network_mode: host
    environment:
      AppSettings__LdapHostnames__0: <LDAP_HOST>
      AppSettings__LdapPort: 636
      AppSettings__LdapUsername: "<PASSCORE_USER>"
      AppSettings__LdapPassword: "<PASSCORE_PW>"
      AppSettings__LdapSecureSocketLayer: "true"
      AppSettings__LdapIgnoreTlsValidation: "true"
      AppSettings__LdapSearchBase: "<LDAP_SEARCH_BASE>"
```

- Log:
```
passcore_1  | Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Zyborg.PassCore.PasswordProvider.LDAP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
passcore_1  | 
passcore_1  | File name: 'Zyborg.PassCore.PasswordProvider.LDAP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
passcore_1  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
passcore_1  |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
passcore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
passcore_1  |    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
passcore_1  |    at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
passcore_1  |    at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
passcore_1  |    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
passcore_1  |    at Unosquare.PassCore.Web.Startup.Main(String[] args) in /src/src/Unosquare.PassCore.Web/Startup.cs:line 50
passcore_passcore_1 exited with code 139
```

**Describe the bug**
The container does not start, Zyborg.PassCore.PasswordProvider.LDAP can not be found.

**To Reproduce**
Start the docker container.

**Expected behavior**
The container should start.
