### ISSUE TITLE
Unable to find username

### ISSUE THREAD

**Issue by blasphemite** [unosquare/passcore#628]
**PassCore Server**
- OS: Linux
- Provider: Active Directory
- Settings file (without sensitive information): 

docker-compose.yml:
```
passcore:
        container_name: passcore
        ports:
            - 80:80
        env_file:
            - ./.env
        environment:
            - WebSettings__EnableHttpsRedirect=false
            - AppSettings__UseAutomaticContext=false
            - AppSettings__LdapHostnames__0=domain.example.com
            - AppSettings__LdapSecureSocketLayer=true
            - AppSettings__LdapPort=636
            - AppSettings__LdapUsername=passcore@domain.example.com
            - AppSettings__LdapIgnoreTlsErrors=true
            - AppSettings__LdapIgnoreTlsValidation=true
            - AppSettings__AllowADGroups__0=Password Web Reset
            - AppSettings__DefaultDomain=domain.example.com
            - ClientSettings__UseEmail=false
        image: passcore:latest
```

env file contains `AppSettings__LdapPassword`

- Log file (without sensitive information): 
```
warn: PassCoreLDAPProvider[0]
      LDAP query: (sAMAccountName=testuser)
warn: PassCoreLDAPProvider[0]
      Unable to find username: [testuser]
```

**Describe the bug**
Double checking my configuration because I'm unable to get around "unable to find username" error. testuser user is a member of AD domain & group "Password Web Reset", passcore user has delegated password permissions.

Attempted `UseEmail=false` without `DefaultDomain` set and get the same error in logs. Also attempted same configuration but without `AllowADGroups` set; same error. Am I missing something? After combing through previous issues I was able to get through previous configuration errors, but not this one.
